
OPTIONS http://localhost:8800/fake/api/auth/login/
###
GET  http://localhost:8000/messages

###
GET  http://localhost:8800/users/1/freinds

###
POST  http://localhost:8800/users/login?success=true

###

GET  http://localhost:8800/api/users/